name: Build Client
on: [push]
jobs:
  desktop:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        include:
          - os: windows-latest
            output-name: drc.exe
            platfrom: windows
            bundle-path: build/windows/runner/release
            
    steps:
      - name: Check Out Code
        uses: actions/checkout@v2
      - run: sudo apt-get install clang cmake ninja-build pkg-config libgtk-3-dev libblkid-dev liblzma-dev
        if: matrix.os == 'ubuntu-latest'
      - name: Setup Flutter
        uses: subosito/flutter-action@v1
      - run: mkdir build
      - run: flutter config --enable-${{ matrix.platfrom }}-desktop
      - run: flutter pub get --no-sound-null-safety
      - run: dart compile exe bin/drc.dart -v -o build/${{ matrix.output-name }} --no-sound-null-safety
      - run: flutter build ${{ matrix.platfrom }} --no-sound-null-safety
      - name: Upload Command Tools
        uses: actions/upload-artifact@v4
        with:
          name: drc-cli-${{ matrix.platfrom }}
          path: build/${{ matrix.output-name }}
      - name: Upload Client
        uses: actions/upload-artifact@v4
        with:
          name: drc-client-${{ matrix.platfrom }}
          path: ${{ matrix.bundle-path }}
