name: Direct Service Docker
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Flutter
        uses: subosito/flutter-action@v1
      - run: flutter config --enable-web
      - run: flutter pub get
      - run: dart compile exe bin/drcd.dart -v -o docker/drcd
      - run: flutter build web
      - run: mv build/web docker/web
      - run: echo $DOCKER_PASSWORD | docker login -u xausky --password-stdin
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t xausky/drcd:${GITHUB_REF##*/} docker
      - run: docker push xausky/drcd:${GITHUB_REF##*/}